# This general role is being used by multiple properties.
# `main` and `wiki` have their own backup tasks due to special requirements.

# It creates a local restore directory and restores the backup using Restic.

# Example usage:
# - name: Run restore tasks
#   include_role:
#     name: restore_property
#   vars:
#     property: property-name
#     backup_path: "{{ property_document_root_path }}"

- name: Create temporary local restore directory if it doesn't exist
  file:
    path: "{{ restore_dir }}"
    state: directory
    mode: "755"

- name: Restore backup
  command: >
    restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }}
    restore latest --target {{ restore_dir }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ DO_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ DO_secret_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"

- name: Find all .tar.bz2 files in the source directory
  find:
    paths: "{{ restore_dir }}"
    patterns: "*.tar.bz2"
  register: tar_files

- name: Extract each .tar.bz2 file
  unarchive:
    src: "{{ item }}"
    dest: "{{ restore_dir }}"
    remote_src: yes
  loop: "{{ tar_files.files | map(attribute='path') | list }}"

- name: Copy restored data to the doc root
  copy:
    src: "{{ restore_dir }}/{{ backup_path }}/"
    dest: "{{ backup_path }}"
    remote_src: yes

- name: Remove temporary restore directory
  file:
    path: "{{ restore_dir }}"
    state: absent
