# This role is being used by multiple properties. It creates a local restore directory and restore backup using Restic.

# Example usage:
# - name: Run restore tasks
#   include_role:
#     name: restore_property
#   vars:
#     property: property-name
#     backup_path: "{{ property_document_root_path }}"

- name: Create temporary local restore directory if it doesn't exist
  file:
    path: "{{ restore_dir }}/{{ restore_name }}"
    state: directory
    mode: "755"

- name: Restore backup
  command: >
    restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }}
    restore latest --target {{ restore_dir }}
  environment:
    AWS_ACCESS_KEY_ID: "{{ DO_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ DO_secret_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"

- name: Extract the .tar backup file
  unarchive:
    src: "{{ restore_dir }}/local/backups/{{ restore_name }}.tar.bz2"
    dest: "{{ restore_dir }}/{{ restore_name }}"
    remote_src: yes

- name: Copy restored data to the doc root
  copy:
    src: "{{ restore_dir }}/{{ restore_name }}"
    dest: "{{ backup_path }}"

- name: Remove temporary restore directory
  file:
    path: "{{ restore_dir }}/{{ restore_name }}"
    state: absent
