- name: Run backup tasks
  include_role:
    name: backup_property
  vars:
    property: shared
    backup_dir:  "{{ backup_dir }}"
    backup_name: "shared-{{ ansible_date_time.date }}"
    domain: "{{ shared_domain }}"
    docroot: "{{ shared_docroot }}"
    