- name: Install Apache with mod-php, php and openssl
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
      - apache2-utils
    state: present
    update_cache: yes

- name: Enable SSL module in Apache
  command: a2enmod ssl
  notify: reload apache

- name: Create the self-signed SSL Certificate
  include_role:
    name: add_self-signed_certs

- name: Add Apache config for shared.php.net
  template:
    src: templates/shared.php.net.conf
    dest: /etc/apache2/sites-available/shared.php.net.conf
  notify: reload apache

- name: Enable Apache PHP module
  command: a2enmod php8.2
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes


