- name: Install Apache with mod-php, php and openssl
  apt:
    pkg:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
      - openssl
      - apache2-utils
    state: present
    update_cache: yes

- name: Add Apache config for shared.php.net
  template:
    src: templates/shared.php.net.conf
    dest: /etc/apache2/sites-available/shared.php.net.conf
  notify: reload apache

- name: Enable Apache PHP module
  command: a2enmod php8.2
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Run self-signed certificate tasks
  include_tasks: self-signed-certs.yml
