- name: Install software
  apt:
    name:
    - git
    - php8.2-cli
    - php8.2-xml
    - php8.2-sqlite3
    state: present
    update_cache: yes

- name: Link /local/this-box to {{ rsync_box_volume }}
  file:
    state: link
    src: "{{ rsync_box_volume }}"
    dest: "/local/this-box"
    mode: "755"
    owner: "root"

- name: Create local dirs
  file:
    state: directory
    dest: "{{ item }}"
    mode: "755"
  loop:
    - "{{ rsync_box_dir }}"
    - "{{ rsync_repositories_dir }}"
    - "{{ rsync_repositories_dir }}/phpdoc-git"
    - "{{ rsync_repositories_dir }}/phpdoc"
    - "{{ rsync_mirrors_dir }}"

- name: Put update scripts to server
  template:
    src: templates/{{ item }}
    dest: /local/systems/
    mode: "755"
  loop:
    - build-docs-lang-rsync
    - build-docs-rsync
    - gen-phpweb-sqlite-db.php
    - git-clone
    - update-everything
    - update-mirrors
    - update-phpweb-backend

- name: Create rsyncd configuration file
  template:
    dest: /etc/rsyncd.conf
    src: templates/rsynd.conf

- name: Start and enable rsync deamon
  service:
    name: rsync
    state: started
    enabled: yes

# Initially clone all repositories. This task will not run if "{{ rsync_box_dir }}/repositories/phpweb/.git exists
- name: Git clone everything
  command: /local/systems/git-clone
  args:
    creates: "{{ rsync_box_dir }}/repositories/phpweb/.git"

# At 0, 10, 20, 30, 40, and 50 minutes past the hour, between 00:00 and 22:50
- name: Update everything cron
  cron:
    name: Update everything
    minute: "0,10,20,30,40,50"
    hour: "0-22"
    job: "/local/systems/update-everything >/var/log/update-everything.log"
    user: root

# Every 2 hours
- name: Build-docs-rsync cron
  cron:
    name: Build docs rsync
    minute: "7"
    hour: "*/2"
    job: /local/systems/build-docs-rsync
    user: root
