- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Create local dirs
  file:
    state: directory
    dest: /local/{{ item }}
    mode: '750'
  loop:
    - mirrors
    - repos

- name: Put update scripts to server
  template:
    src: templates/{{ item }}
    dest: /local/systems/
    mode: '750'
  loop:
    - update-everything
    - update-mirrors
    - update-phpweb-backend
    - build-docs-rsync
    - git-clone

- name: Create rsyncd configuration file
  template:
    dest: /etc/rsyncd.conf
    src: templates/rsynd.conf

- name: Start and enable rsync deamon
  service:
    name: rsync
    state: started
    enabled: yes

# Initially clone all repositories. This task will not run if /local/repos/phpweb/.git exists
- name: Git clone everything
  shell: /local/systems/git-clone
  args:
    creates: /local/repos/phpweb/.git

# At 0, 10, 20, 30, 40, and 50 minutes past the hour, between 12:00 AM and 10:59 PM
- name: Update everything cron
  cron:
    name: "Update everything"
    minute: "0,10,20,30,40,50"
    hour: "0-22"
    job: "/local/systems/update-everything > /dev/null"
    user: "root"

# Every 2 hours
- name: Build-docs-rsync cron
  cron:
    name: "Build docs rsync"
    minute: "0"
    hour: "*/2"
    job: "/local/systems/build-docs-rsync"
    user: "root"

# The script is added by update-mirror
# Fridays at 09:10 AM
- name: fetch-chms.php cron
  cron:
    name: "Fetch CHMs"
    minute: "10"
    hour: "9"
    day: "*"
    month: "*"
    weekday: "5"
    job: "php /local/repos/phpdoc-git/doc-base/scripts/fetch-chms.php"
    user: "root"
