# The wiki property doesn't use the global `backup_property` role because the case is a bit special here:
# 2 folders are backed up and the prune also differs.

# These tasks create a /local/backup folder.
# Create a cronjob to compress the data from wiki's homedir into it, loads the compesses data up to S3 and removes it afterwards.
# Create another cron to prune backups, to keep only the last 2 ones on S3 storage
# Backup logs can be found at /local/systems/backup.log

# Reference backup script: https://github.com/php/systems/blob/master/backup-wiki-php-net

- name: Install bzip2
  apt:
    name: bzip2
    state: present
    update_cache: yes

- name: Ensure backup directory exist
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "755"

# the next tasks are for test purposes and can be removed once proper data is added to the machine
#- include_tasks: add_testData.yml

# Initialize Restic for both data and media folders
- name: Initialize Restic
  command:
    cmd: "restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/wiki-data init"
  environment:
    AWS_ACCESS_KEY_ID: "{{ DO_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ DO_secret_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
  # Only fail when the error is not: already initialized
  register: restic_init_result
  failed_when: >
    restic_init_result.rc != 0 and
    'repository master key and config already initialized' not in restic_init_result.stderr
  changed_when: restic_init_result.rc == 0

- name: Create backup script
  template:
    src: templates/backup-wiki
    dest: /local/systems/backup-wiki
    mode: "755"

- name: Create restore script
  template:
    src: templates/restore-wiki
    dest: /local/systems/restore-wiki
    mode: "755"

- name: Create daily property backup
  cron:
    name: Daily property backup
    job: /local/systems/backup-wiki
    special_time: daily
    state: present

- name: Daily prune wiki, keep only the last 30 backups
  cron:
    name: Daily prune wiki
    job: |
      AWS_ACCESS_KEY_ID="{{ DO_access_key }}" AWS_SECRET_ACCESS_KEY="{{ DO_secret_key }}" RESTIC_PASSWORD="{{ restic_password }}" restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/wiki-data forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune
    state: present
    special_time: daily
