- name: Run backup tasks
  include_role:
    name: backup_property
  vars:
    property: wiki
    backup_dir:  "{{ backup_dir }}"
    backup_name: "wiki-{{ ansible_date_time.date }}"
    domain: "{{ wiki_domain }}"
    docroot: "{{ wiki_docroot }}"
