- name: Create local directory to store wiki content
  file:
    state: directory
    dest: "{{ wiki_data_dir }}"
    mode: "755"
    owner: www-data
    group: www-data
    recurse: yes

- name: Create local directores for dokuwiki data elements
  file:
    state: directory
    dest: "{{ wiki_data_dir }}/{{ item }}"
    mode: "755"
    owner: www-data
    group: www-data
    recurse: yes
  loop:
   - log
   - cache

- name: Copy update-wiki script to the server
  template:
    src: templates/update-wiki
    dest: /local/systems/update-wiki
    mode: "700"

- name: Fetch wiki content
  command: /local/systems/update-wiki

- name: Deploy wiki hourly
  cron:
    name: Run update-wiki hourly
    special_time: hourly
    job: /local/systems/update-wiki

