- name: Create local directory to store wiki content
  file:
    state: directory
    dest: "{{ wiki_docroot }}"
    mode: '755'
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy update-wiki script to the server
  template:
    src: templates/update-wiki
    dest: /local/systems/update-wiki
    mode: '700'

- name: Fetch wiki content
  command: /local/systems/update-wiki

- name: Update permission of wiki doc root
  file:
    dest: "{{ wiki_docroot }}"
    mode: '755'
    owner: www-data
    group: www-data
    recurse: yes

- name: Create local directory for dokuwiki data log
  file:
    state: directory
    dest: /srv/web-wiki/dokuwiki/dokuwiki/data/log
    mode: '755'
    owner: www-data
    group: www-data
    recurse: yes

- name: Deploy wiki daily
  cron:
    name: Run update-wiki daily
    special_time: daily
    job: /local/systems/update-wiki

# Run restore
# The restore role is commented out when initializing the property for the first time
# This can be commented in when backup data is run at least once and available foe restore
# - include_tasks: restore.yml
