- name: Create local directory to store wiki content
  file:
    state: directory
    dest: "{{ wiki_docroot }}"
    mode: '755'
    owner: www-data
    group: www-data
    recurse: yes

- name: Copy update-wiki script to the server
  template:
    src: templates/update-wiki
    dest: /local/systems/update-wiki
    mode: '700'

- name: Deploy wiki daily
  cron:
    name: "Run update-wiki daily"
    minute: "0"
    hour: "0"
    day: "*"
    job: "/local/systems/update-wiki"
