- name: Install Apache with mod-php, php
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
    state: present
    update_cache: yes

# Headers module used in wiki.conf and needs to be enabled
- name: Create symlink to enable headers module in config file
  file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link

- name: Add Apache config for wiki
  template:
    src: templates/wiki.conf
    dest: /etc/apache2/sites-available/wiki.conf
  notify: reload apache

# FIXME: this sometimes doesn't work. Then we have to disable mpm_event and Enable mpm_prefork defore running this
# sudo a2dismod mpm_event
# sudo a2enmod mpm_prefork
- name: Enable Apache PHP module
  shell: a2enmod php8.2
  notify: reload apache

# because we run certbot with certonly, and we use Rewrite in our apache config
# we have to enable this
- name: Enable Rewrite module in Apache
  command: a2enmod rewrite
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Run certbot tasks
  include_role:
    name: add_certbot
  vars:
    domain: "{{ wiki_domain }}"
    config_file: wiki.conf
    email: "{{ systems_email }}"


- include_tasks: deploy.yml
