# This role sets up the property wiki.php.net with Apache together with the php module
# It uses certbot SSL certs

- name: Add Apache config for wiki
  template:
    src: templates/wiki.conf
    dest: "/etc/apache2/sites-available/{{ wiki_config_file }}"
  notify: reload apache

- name: Enable config file
  shell: "a2ensite {{ wiki_config_file }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ wiki_config_file }}"
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

- name: Run backup tasks
  include_role:
    name: backup_property
  vars:
    property: wiki
    backup_path: '{{ wiki_data_dir }}'

# This can be run when backup data is run at least once and available for restore
# The restore role will only be run, when you pass --extra-vars "restore_data=true"
- name: Run restore tasks
  include_role:
    name: restore_property
  vars:
    property: wiki-data
    backup_path: '{{ wiki_data_dir }}'
  when: restore_data is defined and restore_data
