# This role sets up the property wiki.php.net with Apache together with the php module
# It uses certbot SSL certs

- name: Install Apache with mod-php and php
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
    state: present
    update_cache: yes

- name: Run certbot tasks
  include_role:
    name: add_certbot
  vars:
    domain: "{{ wiki_domain }}"
    email: "{{ systems_email }}"

- name: Add Apache config for wiki
  template:
    src: templates/wiki.conf
    dest: "/etc/apache2/sites-available/{{ wiki_config_file }}"
  notify: reload apache

# because we run certbot with certonly, and we use Rewrite in our apache config
# we have to enable this
- name: Enable Apache PHP module
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - php8.2
    - headers
    - rewrite
  notify: reload apache

- name: Enable config file
  shell: "a2ensite {{ wiki_config_file }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ wiki_config_file }}"
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

- include_tasks: backup.yml

# This can be run when backup data is run at least once and available for restore
# The restore role should be skipped when initializing the property for the first time with --extra-vars "first_run=true"
- include_tasks: restore.yml
  when: first_run is not defined or not first_run
