# The wiki property doesn't use the global `restore_property` role because 2 folders are restored.

# Add restore backup tasks
# These tasks create a /local/restore folder.
# It calls restic to take the latest backup and restore it to /local/restore.
# It extracts it, restores the db and deletes the restore folder again.

- name: Create a local restore directory
  file:
    path: "{{ restore_dir }}"
    state: directory
    mode: "755"

- name: Restore backup
  command: /local/systems/restore-wiki

- name: Remove temporary restore directory
  file:
    path: "{{ restore_dir }}"
    state: absent

