- name: Install Apache with mod-php, php, cli-php and mariaDB
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
      - php8.2-cli
      - mariadb-server
    state: present
    update_cache: yes

- name: create local box
  file:
    state: directory
    dest: /local/this-box
    mode: '750'

- name: Store secrets file
  template:
    src: templates/secrets.conf
    dest: /local/this-box/apache.conf
    mode: '600'
    owner: www-data
    group: www-data

- name: Add Apache config for main.php.net
  template:
    src: templates/main.php.net.conf
    dest: /etc/apache2/sites-available/main.php.net.conf
  notify: reload apache

- name: Enable Apache modules
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.conf
  loop:
    - rewrite
    - php8.2
  notify: reload apache

- name: Enable config file
  command: a2ensite main.php.net.conf
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

# Add backup cronjob
- include_tasks: backup.yml
  vars:
    property: main
    backup_name: "main-{{ ansible_date_time.date }}"
    backup_dir: "{{ backup_dir }}"
