- name: Install Apache with mod-php, php, cli-php and mariaDB
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
      - php8.2-cli
      - mariadb-server
    state: present
    update_cache: yes

# Do we need a file here?
# - name: Create PHP custom configuration for include_path
#   copy:
#     dest: /etc/php/8.0/apache2/conf.d/99-custom.ini
#     content: |
#       ; Custom PHP include_path
#       include_path = ".:/usr/share/php:/custom/include/path"

- name: create local box
  file:
    state: directory
    dest: /local/this-box
    mode: '750'

- name: Store secrets file
  template:
    src: templates/secrets.conf
    dest: /local/this-box/apache.conf
    mode: '600'
    owner: www-data
    group: www-data

- name: Add Apache config for main.php.net
  template:
    src: templates/main.php.net.conf
    dest: /etc/apache2/sites-available/main.php.net.conf
  notify: reload apache

- name: Enable Apache php modules
  command: a2enmod php8.2
  args:
    creates: /etc/apache2/mods-enabled/php8.2.conf
  # loop:
    # - rewrite
    # - php8.2
  notify: reload apache

- name: Enable SSL site
  command: a2ensite main.php.net.conf
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

# Add backup cronjob
- include_tasks: backup.yml
  vars:
    property: main
    backup_name: "main-{{ ansible_date_time.date }}"
    backup_dir: "{{ backup_dir }}"
