- name: Install Apache with mod-php, php, cli-php and mariaDB
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - php8.2
      - php8.2-cli
      - mariadb-server
    state: present
    update_cache: yes

- name: create local box
  file:
    state: directory
    dest: "{{ main_box }}"
    mode: "750"

- name: Store secrets file
  template:
    src: templates/secrets.conf
    dest: "{{ main_box }}/apache.conf"
    mode: "600"
    owner: www-data
    group: www-data

- name: Add Apache config for main.php.net
  template:
    src: templates/main.php.net.conf
    dest: "/etc/apache2/sites-available/{{ main_config_file }}"
  notify: reload apache

- name: Enable Apache modules
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - rewrite
    - php8.2
  notify: reload apache

- name: Enable config file
  shell: "a2ensite {{ main_config_file }}"
  creates: "/etc/apache2/sites-enabled/{{ main_config_file }}"
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

- name: Set mysql root password
  command: mysqladmin -u root password "{{ db_root_password }}"

- name: Create MariaDB database
  command: mysql -u root -p{{ db_root_password }} -e "CREATE DATABASE IF NOT EXISTS {{ db_name }}"
  args:
    creates: "/var/lib/mysql/{{ db_name }}"

- name: Create MySQL user 'nobody' if not exists
  command: mysql -u root -p{{ db_root_password }} -e "CREATE USER IF NOT EXISTS 'nobody'@'localhost' IDENTIFIED BY '';"

- name: Grant privileges to 'nobody' for the specified database
  command: mysql -u root -p{{ db_root_password }} -e "GRANT SELECT, LOCK TABLES ON {{ db_name }}.* TO 'nobody'@'localhost'; FLUSH PRIVILEGES;"

- include_tasks: backup.yml

# This needs to be commented out on the initial run
#- include_tasks: restore.yml

