# Restore backup in local restore directory
- name: Create a local restore directory with today's date
  file:
    path: "{{ restore_dir }}"
    state: directory
    mode: "755"

- name: Restore backup with Restic
  command: restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/main restore latest --target {{ restore_dir }}/
  environment:
    AWS_ACCESS_KEY_ID: "{{ DO_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ DO_secret_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"

- name: Find all .tar.bz2 files in the source directory
  find:
    paths: "{{ restore_dir }}"
    patterns: "*.tar.bz2"
  register: tar_files

- name: Extract each .tar.bz2 file
  unarchive:
    src: "{{ item }}"
    dest: "{{ restore_dir }}"
    remote_src: yes
  loop: "{{ tar_files.files | map(attribute='path') | list }}"

- name: Restore MySQL database from the dump
  shell: "mysql -u nobody {{ db_name }} < {{ item | regex_replace('(.tar.bz2)$', '')}}/{{ db_name }}.sql"
  loop: "{{ tar_files.files | map(attribute='path') | list }}"

- name: Remove temporary restore directory
  file:
    path: "{{ restore_dir }}"
    state: absent
