#!/bin/bash

php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php pecl:add {{ windows_builds_options }} 
php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php php:add {{ windows_builds_options }}
php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php winlibs:add {{ windows_builds_options }}
php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php series:init {{ windows_builds_options }}
php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php series:delete {{ windows_builds_options }}
php {{ downloads_docroot }}/{{ downloads_domain }}/runner.php series:stability {{ windows_builds_options }}
