# This property redirects to https://heap.space

- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Add Apache config for lxr.php.net
  template:
    src: templates/lxr.php.net.conf
    dest: /etc/apache2/sites-available/lxr.php.net.conf
  notify: reload apache

- name: Enable Rewrite module in Apache
  command: a2enmod rewrite
  args:
    creates: /etc/apache2/mods-enabled/rewrite.load
  notify: reload apache

- name: Enable config file
  shell: a2ensite lxr.php.net.conf
  args:
    creates: /etc/apache2/sites-enabled/lxr.php.net.conf
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
