Core:
  Listen: ":8991"
  Secret: "{{ ohdear_secret }}"

LoadAverage:
  Warning: 10
  Error: 20

MemoryUsagePercent:
  Warning: 80
  Error: 90

DiskUsagePercent:
  Warning: 80
  Error: 90

TCPServices:
- Description: "SMTP 25"
  Port: "mailout.php.net:25"
  ErrorThresholdMins: 3
