- name: Install Apache with mod-php, php and openssl
  apt:
    name:
      - apache2
      - libapache2-mod-php8.2
      - apache2-utils
      - php8.2
      - php8.2-bz2
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-xml
    state: present
    update_cache: yes

- name: Create the self-signed SSL Certificate
  include_role:
    name: add_self-signed_certs

- name: Enable modules in Apache
  command: a2enmod {{ item }}
  args:
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - ssl
    - php8.2
    - headers
    - rewrite
    - remoteip
  notify: reload apache

- name: Add remoteip logging config
  template:
    src: templates/{{ mod_remoteip_config_file }}
    dest: "/etc/apache2/conf-enabled/{{ mod_remoteip_config_file }}"
  notify: reload apache

- name: Add opcache and other local PHP settings
  template:
    src: templates/90-local-settings.ini
    dest: /etc/php/8.2/apache2/conf.d/90-local-settings.ini
  notify: reload apache
