#!/bin/sh

file=/tmp/.dns.$$

if php /local/systems/maintain-master-dns.php > $file ; then
	if /usr/bin/named-checkzone php.net $file ; then
		mv -f $file "{{ bind_php_net_zone_file }}"
		systemctl reload bind9
	fi
fi
