# This general role is being used by multiple properties.
# `main` and `wiki` have their own backup tasks due to special requirements.

# It creates a local backup directory and makes a backup of the root folder using Restic.
# After the compressed data us backed up to S3, it gets removed from the system again.
# Backup logs can be found at /local/systems/backup.log
# The {{ property }} var has to match the bucket's folder.

# Example usage:
# - name: Run backup tasks
#   include_role:
#     name: backup_property
#   vars:
#     property: property-name
#     backup_paths: [ "{{ property_document_root_path }}" ]

- name: Create temporary local backup directory if it doesn't exist
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "755"

- name: Install bzip2
  apt:
    name: bzip2
    state: present
    update_cache: yes

- name: Initialize Restic
  command:
    cmd: restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }} init
  environment:
    AWS_ACCESS_KEY_ID: "{{ DO_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ DO_secret_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
  # Only fail when the error is not: already initialized
  register: restic_init_result
  failed_when: >
    restic_init_result.rc != 0 and
    'repository master key and config already initialized' not in restic_init_result.stderr
  changed_when: restic_init_result.rc == 0

- name: Create backup script
  template:
    src: "{{ role_path }}/templates/backup-property"
    dest: "/local/systems/backup-{{ property }}"
    mode: "755"

- name: Create daily property backup
  cron:
    name: "Daily property backup for {{ property }}"
    job: "/local/systems/backup-{{ property }}"
    special_time: daily
    state: present

- name: Daily prune old backups
  cron:
    name: Daily prune old backups
    job: |
      AWS_ACCESS_KEY_ID="{{ DO_access_key }}" AWS_SECRET_ACCESS_KEY="{{ DO_secret_key }}" RESTIC_PASSWORD="{{ restic_password }}" restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/{{ property }} forget --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prune
    state: absent
    special_time: daily
