# The following sets up self-signed SSL certificate, enables SSL site
# and schedules automatic renewal of the

- name: Install required packages
  apt:
    name:
      - openssl
      - apache2-utils
    state: present
    update_cache: yes

- name: Generate private key
  command: >
    openssl genrsa -out /etc/ssl/certs/apache-self-signed.key 2048
  args:
    creates: /etc/ssl/certs/apache-self-signed.key

- name: Generate self-signed certificate
  command: >
    openssl req -new -x509 -key /etc/ssl/certs/apache-self-signed.key
    -out /etc/ssl/certs/apache-self-signed.crt
    -days 365
    -subj "/C=US/ST=State/L=City/O=php/OU=Unit/CN=php.net"
  args:
    creates: /etc/ssl/certs/apache-self-signed.crt

- name: Enable SSL module in Apache
  command: a2enmod ssl
  notify: reload apache
