- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present
    update_cache: yes

- name: Add Apache config
  template:
    src: templates/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: restart apache # this calls the handler

# - name: Update Apache to latest version
#   ansible.builtin.apt:
#     name: apache2
#     state: latest
#     update_cache: yes
#   notify: restart apache

# - name: Remove Apache
#   ansible.builtin.package:
#     name: apache2* # wildcard removes dependencies
#     state: absent
#     autoremove: yes
#     purge: true
