#!/bin/sh

# Redirect all output to the backup.log
DOW=`date +%w`
exec > "/local/systems/backup-${DOW}.log" 2>&1

cd {{ backup_dir }}

echo "[$(date)] Starting backup process..."

# Environment Variables
export AWS_ACCESS_KEY_ID="{{ DO_access_key }}"
export AWS_SECRET_ACCESS_KEY="{{ DO_secret_key }}"
export RESTIC_PASSWORD="{{ restic_password }}"

# Compress wiki data
tar cfP - {{ wiki_data_dir }} | bzip2 -9 > {{ backup_name }}.tar.bz2
echo "[$(date)] Data compression completed."

# S3 Upload: wiki data
restic -r s3:{{ DO_bucket_url }}/{{ DO_bucket_name }}/wiki-data backup {{ backup_name }}.tar.bz2
exit_status=$?
echo "restic status for data: " $exit_status

if [ $exit_status -eq 0 ]; then
  echo "[$(date)] S3 upload completed."

  # Remove local backup data
  rm -rf {{ backup_dir }}/*
  echo "[$(date)] Cleanup completed."

  echo "[$(date)] Backup process finished successfully."

else
  echo "[$(date)] Could not upload data."
fi
