# This role sets up the property talks.php.net with Apache together with the php module
# It uses self-signed SSL certs

- name: Add Apache config for talks.php.net
  template:
    src: templates/{{ talks_config_file }}
    dest: "/etc/apache2/sites-available/{{ talks_config_file }}"
  notify: reload apache

- name: Enable config file
  shell: "a2ensite {{ talks_config_file }}"
  args:
    creates: "/etc/apache2/sites-enabled/{{ talks_config_file }}"
  notify: reload apache

- name: Add Apache config for aliases
  template:
    src: templates/{{ talks_redirect_config_file }}
    dest: "/etc/apache2/sites-available/{{ item }}.php.net.conf"
  loop: "{{ talks_old_aliases }}"
  notify: reload apache

- name: Enable config files for aliases
  shell: "a2ensite {{ item }}.php.net.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ item }}.php.net.conf"
  loop: "{{ talks_old_aliases }}"
  notify: reload apache

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- include_tasks: deploy.yml

