- name: Get all users
  getent:
    database: passwd
    split: ':'

- name: Check if user exists
  fail:
    msg: "User does not exist"
  when: username not in getent_passwd.keys()

- name: Delete an existing linux user
  user:
    name: "{{ username }}"
    state: absent
    remove: yes
