- name: Create local directory to store museum content
  file:
    state: directory
    dest: "{{ museum_docroot }}/{{ museum_domain }}"
    mode: "755"
    recurse: yes

- name: Fetch content for museum
  command: "rsync -avz {{ museum_source }}/ {{ museum_docroot }}/{{ museum_domain }}/"

