# This restarts the Apache service
- name: restart apache
  service:
    name: apache2
    state: restarted

# This reloads the Apache service
- name: reload apache
  service:
    name: apache2
    state: reloaded
