www_docroot: /var/www/sites/www.php.net
www_config_file: www.php.net.conf

# For the aliases where www was also configured, we set up redirects
www_redirect_config_file: www-redirect.php.net.conf
www_old_aliases: [ "static", "secure" ]
